<a href="https://colab.research.google.com/github/seupedro7/Trainee-CIS/blob/main/Trainee_CIS_Parte_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##KNN usando Numpy

In [38]:
import numpy as np
from math import sqrt
from collections import Counter

In [55]:

def distancia_euclidiana(x1,x2):
  distancia = np.linalg.norm(x1-x2)
  return distancia

In [3]:
def get_neighbors (treino,teste,nvisinhos):
  distancias = list()
  for train_row in treino:
    d = distancia_euclidiana(teste, train_row)
    distancias.append((train_row,d))
  d.sort(key=lambda tup:tup[1])
  visinhos = list()
  for i in range(nvisinhos):
    visinhos.append(distancias[i][0])
  return visinhos

In [59]:
def Xknn (x_teste, x_treino, y_treino, k):
  final_output = []
  for i in range(len(x_teste)):       ## Pega os índices dos dados de teste
    d = []
    votes = []
    for j in range(len(x_treino)):    ##Pega os índices dos dados do treino e compara cada um com o dado teste
      dist = distancia_euclidiana(x_treino[j] , x_teste[i])    #Calcula a distancia
      d.append([dist, j])             ##Registra aqui na lista a distancia e o indice do treino
    d.sort()                          #Ordena a lista e pega apenas até a distancia k
    d = d[0:k]
    for d, j in d:
      votes.append(y_treino[j])        #Pega da lista os valores um por um e coloca o valor de y correspondente do treino
    ans = Counter(votes).most_common(1)[0][0]  #Pega apenas o elemento que mais que aparece
    final_output.append(ans)          #Devolve pra nós o elemento em uma lista.
            
  return final_output

def score(y_teste,prev):
  cont = 0
  for i in range(len(prev)):
    if prev[i] == y_teste[i]:
      cont += 1
  return cont / len(y_teste)   #Calcula a acurácia. O quanto bateu com o esperado

In [5]:
import pandas as pd

In [6]:
from google.colab import files
up = files.upload()

Saving winequality.csv to winequality.csv

In [42]:
df=pd.read_csv('winequality.csv')


df.describe()

        Unnamed: 0  fixed acidity  ...      quality  wine_is_red
count  6497.000000    6497.000000  ...  6497.000000  6497.000000
mean   3248.000000       7.215307  ...     5.818378     0.246114
std    1875.666681       1.296434  ...     0.873255     0.430779
min       0.000000       3.800000  ...     3.000000     0.000000
25%    1624.000000       6.400000  ...     5.000000     0.000000
50%    3248.000000       7.000000  ...     6.000000     0.000000
75%    4872.000000       7.700000  ...     6.000000     0.000000
max    6496.000000      15.900000  ...     9.000000     1.000000

[8 rows x 14 columns]

In [8]:
df=df.drop(columns=['Unnamed: 0'])
df = df.drop_duplicates()
df.describe()

       fixed acidity  volatile acidity  ...      quality  wine_is_red
count    5320.000000       5320.000000  ...  5320.000000  5320.000000
mean        7.215179          0.344130  ...     5.795677     0.255451
std         1.319671          0.168248  ...     0.879772     0.436155
min         3.800000          0.080000  ...     3.000000     0.000000
25%         6.400000          0.230000  ...     5.000000     0.000000
50%         7.000000          0.300000  ...     6.000000     0.000000
75%         7.700000          0.410000  ...     6.000000     1.000000
max        15.900000          1.580000  ...     9.000000     1.000000

[8 rows x 13 columns]

In [9]:
from sklearn import preprocessing
df2=df.drop(columns=['wine_is_red','quality'])  
nrm_scaler = preprocessing.MinMaxScaler()

 
df_scaled = nrm_scaler.fit_transform(df2.to_numpy())
df_scaled = pd.DataFrame(df_scaled, columns=['fixed acidity',	'volatile acidity',	'citric acid',	'residual sugar',	'chlorides'	,'free sulfur dioxide',	'total sulfur dioxide'	,'density',	'pH',	'sulphates',	'alcohol'])
df_scaled['wine_is_red'] = df['wine_is_red']
df_scaled['quality'] = df['quality']
df_scaled = df_scaled.dropna()
df_scaled.describe()

       fixed acidity  volatile acidity  ...  wine_is_red      quality
count    4498.000000       4498.000000  ...  4498.000000  4498.000000
mean        0.281875          0.175170  ...     0.257225     5.793241
std         0.108602          0.110955  ...     0.437153     0.873308
min         0.000000          0.000000  ...     0.000000     3.000000
25%         0.214876          0.100000  ...     0.000000     5.000000
50%         0.264463          0.140000  ...     0.000000     6.000000
75%         0.322314          0.220000  ...     1.000000     6.000000
max         0.975207          1.000000  ...     1.000000     9.000000

[8 rows x 13 columns]

In [16]:
X = df_scaled[['fixed acidity',	'volatile acidity',	'citric acid',	'residual sugar',	'chlorides'	,'free sulfur dioxide',	'total sulfur dioxide'	,'density',	'pH',	'sulphates',	'alcohol','wine_is_red']]

y = df_scaled[['quality']]

features = ['fixed acidity',	'volatile acidity',	'citric acid',	'residual sugar',	'chlorides'	,'free sulfur dioxide',	'total sulfur dioxide'	,'density',	'pH',	'sulphates',	'alcohol','wine_is_red']
X.head()

   fixed acidity  volatile acidity  ...   alcohol  wine_is_red
0       0.173554          0.353333  ...  0.449275          1.0
1       0.363636          0.613333  ...  0.144928          1.0
2       0.214876          0.106667  ...  0.362319          0.0
3       0.231405          0.100000  ...  0.289855          0.0
4       0.280992          0.106667  ...  0.304348          0.0

[5 rows x 12 columns]

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train ,y_test = train_test_split(X,y,random_state =0)

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=30)

In [19]:
knn.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=30)

In [20]:
resultado = knn.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score
print('Acurácia do modelo: ' , accuracy_score(y_test, resultado))

Acurácia do modelo:  0.4222222222222222

In [46]:
from sklearn.preprocessing import StandardScaler

x = df[['fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']]

x = x.to_numpy()

y = df['wine_is_red']

y = y.to_numpy()
#Geramos as mesmas variáveis normalizadas

standardizer = StandardScaler()

x_norm = standardizer.fit_transform(x)

X_train, X_test , y_train ,y_test = train_test_split(x_norm,y,random_state =0)

In [48]:
#Setamos a variável que vai dividir os dados em treino e teste

tamanho = len(x)
teste = int(0.2*tamanho)
treino = tamanho - teste 
print('Tamanho do set: ', tamanho)
print('Quantidade de teste: ', teste)
print('Quantidade de treino: ', treino)

Tamanho do set:  6497
Quantidade de teste:  1299
Quantidade de treino:  5198

In [53]:
#Separamos os dados de treino e teste

k = 2
X_train = x[0:treino]
X_test = x[treino:]
y_train = y[0:treino]
y_test = y[treino:]

In [57]:
k=5
resultado2 = Xknn(X_test,X_train, y_train, k)
resultado2

[0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 ...]

In [60]:
#Vemos a eficácia do KNN em prever

score = score(y_test, resultado2)

print(score)

0.9414934565050038

##Teste dos modelos de machine learning
#Support Vector Mmachine

In [ ]:
from sklearn import svm

In [ ]:
cls = svm.SVC(kernel="linear")
cls.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(kernel='linear')

In [ ]:
y_pred = cls.predict(X_test)

In [ ]:
print('Acurácia do modelo: ' , accuracy_score(y_test, y_pred))

Acurácia do modelo:  0.43466666666666665

#Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(max_depth=10, min_samples_split=10, random_state=42)
clf.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=10, min_samples_split=10, random_state=42)

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
print('Acurácia do modelo: ' , accuracy_score(y_test, y_pred))

Acurácia do modelo:  0.39644444444444443

#Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth = 10 , random_state  = 0)
model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

RandomForestClassifier(max_depth=10, random_state=0)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print('Acurácia do modelo: ' , accuracy_score(y_test, y_pred))

Acurácia do modelo:  0.43377777777777776

#Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print('Acurácia do modelo: ' , accuracy_score(y_test, y_pred))

Acurácia do modelo:  0.432